// Copyright (c) 2026 Ahmad Faruk (Signal18 ID). All rights reserved.
// Ownership: Ahmad Faruk (Signal18 ID)

/**
 * AP Reconciliation Snapshots API adapter.
 *
 * Delegates to @jurnapod/modules-purchasing services.
 * This file is a thin adapter — all business logic lives in the package.
 */

import { getDb } from "../db.js";
import { ApReconciliationSnapshotService } from "@jurnapod/modules-purchasing";
import type {
  APReconciliationSnapshotRecord,
  SnapshotListFilters,
  SnapshotCompareResult,
} from "@jurnapod/modules-purchasing";

// Re-export types for use in routes
export type {
  APReconciliationSnapshotRecord,
  SnapshotListFilters,
  SnapshotCompareResult,
};

// Re-export error classes for use in routes
export {
  APReconciliationSnapshotNotFoundError,
  APReconciliationSnapshotCompareCrossTenantError,
} from "@jurnapod/modules-purchasing";

export async function createAPReconciliationSnapshot(input: {
  companyId: number;
  asOfDate: string;
  createdBy: number;
  autoGenerated?: boolean;
  reason?: string;
}): Promise<APReconciliationSnapshotRecord> {
  const db = getDb();
  const service = new ApReconciliationSnapshotService(db);
  return service.createAPReconciliationSnapshot(input);
}

export async function listAPReconciliationSnapshots(
  companyId: number,
  filters: SnapshotListFilters
): Promise<{ items: APReconciliationSnapshotRecord[]; totalCount: number }> {
  const db = getDb();
  const service = new ApReconciliationSnapshotService(db);
  return service.listAPReconciliationSnapshots({ companyId, filters });
}

export async function getAPReconciliationSnapshotById(
  companyId: number,
  snapshotId: number
): Promise<APReconciliationSnapshotRecord> {
  const db = getDb();
  const service = new ApReconciliationSnapshotService(db);
  return service.getAPReconciliationSnapshotById({ companyId, snapshotId });
}

export async function compareAPReconciliationSnapshots(input: {
  companyId: number;
  snapshotId: number;
  withSnapshotId: number;
}): Promise<SnapshotCompareResult> {
  const db = getDb();
  const service = new ApReconciliationSnapshotService(db);
  return service.compareAPReconciliationSnapshots(input);
}

export function generateSnapshotCSV(snapshot: APReconciliationSnapshotRecord): string {
  const header = [
    "snapshot_id",
    "company_id",
    "as_of_date",
    "snapshot_version",
    "auto_generated",
    "account_source",
    "configured_account_ids",
    "ap_subledger_balance",
    "gl_control_balance",
    "variance",
    "timezone",
    "inputs_hash",
    "created_by",
    "created_at",
    "status",
  ];

  const row = [
    String(snapshot.id),
    String(snapshot.companyId),
    snapshot.asOfDate,
    String(snapshot.snapshotVersion),
    snapshot.autoGenerated ? "true" : "false",
    snapshot.accountSource,
    JSON.stringify(snapshot.configuredAccountIds),
    snapshot.apSubledgerBalance,
    snapshot.glControlBalance,
    snapshot.variance,
    snapshot.timezone,
    snapshot.inputsHash,
    String(snapshot.createdBy),
    snapshot.createdAt,
    snapshot.status,
  ];

  const escapeCsv = (value: string): string => {
    if (value.includes(",") || value.includes("\"") || value.includes("\n")) {
      return `"${value.replaceAll("\"", "\"\"")}"`;
    }
    return value;
  };

  return `${header.join(",")}\n${row.map(escapeCsv).join(",")}\n`;
}
