// Copyright (c) 2026 Ahmad Faruk (Signal18 ID). All rights reserved.
// Ownership: Ahmad Faruk (Signal18 ID)

import { createHash } from "node:crypto";
import { sql } from "kysely";
import type { KyselySchema } from "@jurnapod/db";
import { getDb } from "@/lib/db";
import {
  fromScaled4,
  getAPReconciliationSummary,
  resolveCompanyTimezone,
  toScaled,
} from "@/lib/purchasing/ap-reconciliation";

export type SnapshotStatus = "ACTIVE" | "ARCHIVED";

export interface APReconciliationSnapshotRecord {
  id: number;
  companyId: number;
  asOfDate: string;
  timezone: string;
  snapshotVersion: number;
  apSubledgerBalance: string;
  glControlBalance: string;
  variance: string;
  configuredAccountIds: number[];
  accountSource: "settings" | "fallback_company_default" | "none";
  inputsHash: string;
  createdBy: number;
  createdAt: string;
  autoGenerated: boolean;
  status: SnapshotStatus;
  retentionPolicyYears: number | null;
  archivedAt: string | null;
  archiveVersion: string | null;
}

export interface SnapshotListFilters {
  asOfDate?: string;
  startDate?: string;
  endDate?: string;
  autoGenerated?: boolean;
  limit: number;
  offset: number;
}

export interface SnapshotCompareResult {
  baseSnapshot: APReconciliationSnapshotRecord;
  otherSnapshot: APReconciliationSnapshotRecord;
  delta: {
    apSubledgerBalance: string;
    glControlBalance: string;
    variance: string;
  };
  changedFields: string[];
}

export class APReconciliationSnapshotNotFoundError extends Error {
  constructor(snapshotId: number) {
    super(`AP reconciliation snapshot ${snapshotId} not found`);
    this.name = "APReconciliationSnapshotNotFoundError";
  }
}

export class APReconciliationSnapshotCompareCrossTenantError extends Error {
  constructor(baseSnapshotId: number, otherSnapshotId: number) {
    super(
      `Cannot compare snapshots ${baseSnapshotId} and ${otherSnapshotId}: snapshots must belong to the same tenant`
    );
    this.name = "APReconciliationSnapshotCompareCrossTenantError";
  }
}

type SnapshotRow = {
  id: number;
  company_id: number;
  as_of_date: Date | string;
  timezone: string;
  snapshot_version: number;
  ap_subledger_balance: string;
  gl_control_balance: string;
  variance: string;
  configured_account_ids_json: unknown;
  account_source: "settings" | "fallback_company_default" | "none";
  inputs_hash: string;
  created_by: number;
  created_at: Date | string;
  auto_generated: number;
  status: SnapshotStatus;
  retention_policy_years: number | null;
  archived_at: Date | string | null;
  archive_version: string | null;
};

function toDateOnly(value: Date | string): string {
  if (value instanceof Date) {
    return value.toISOString().slice(0, 10);
  }
  return String(value).slice(0, 10);
}

function toIsoDateTime(value: Date | string | null): string | null {
  if (!value) {
    return null;
  }
  if (value instanceof Date) {
    return value.toISOString();
  }
  const asString = String(value);
  return asString.includes("T") ? asString : asString.replace(" ", "T") + "Z";
}

function parseConfiguredAccountIds(value: unknown): number[] {
  if (Array.isArray(value)) {
    return value.map(Number).filter((v) => Number.isSafeInteger(v) && v > 0);
  }

  if (typeof value === "string") {
    try {
      const parsed = JSON.parse(value);
      if (Array.isArray(parsed)) {
        return parsed.map(Number).filter((v) => Number.isSafeInteger(v) && v > 0);
      }
    } catch {
      return [];
    }
  }

  return [];
}

function mapSnapshotRow(row: SnapshotRow): APReconciliationSnapshotRecord {
  return {
    id: Number(row.id),
    companyId: Number(row.company_id),
    asOfDate: toDateOnly(row.as_of_date),
    timezone: String(row.timezone),
    snapshotVersion: Number(row.snapshot_version),
    apSubledgerBalance: String(row.ap_subledger_balance),
    glControlBalance: String(row.gl_control_balance),
    variance: String(row.variance),
    configuredAccountIds: parseConfiguredAccountIds(row.configured_account_ids_json),
    accountSource: row.account_source,
    inputsHash: String(row.inputs_hash),
    createdBy: Number(row.created_by),
    createdAt: toIsoDateTime(row.created_at) ?? new Date(0).toISOString(),
    autoGenerated: Number(row.auto_generated) === 1,
    status: row.status,
    retentionPolicyYears: row.retention_policy_years === null ? null : Number(row.retention_policy_years),
    archivedAt: toIsoDateTime(row.archived_at),
    archiveVersion: row.archive_version ?? null,
  };
}

function computeDelta(a: string, b: string): string {
  const left = toScaled(a, 4);
  const right = toScaled(b, 4);
  return fromScaled4(right - left);
}

function normalizeDateOnly(date: string): string {
  const trimmed = String(date).trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) {
    throw new Error(`Invalid date format: ${date}. Expected YYYY-MM-DD`);
  }
  return trimmed;
}

function computeInputsHash(input: {
  companyId: number;
  asOfDate: string;
  timezone: string;
  configuredAccountIds: number[];
  accountSource: string;
  apSubledgerBalance: string;
  glControlBalance: string;
  variance: string;
}): string {
  const payload = JSON.stringify({
    company_id: input.companyId,
    as_of_date: input.asOfDate,
    timezone: input.timezone,
    configured_account_ids: [...input.configuredAccountIds].sort((a, b) => a - b),
    account_source: input.accountSource,
    ap_subledger_balance: input.apSubledgerBalance,
    gl_control_balance: input.glControlBalance,
    variance: input.variance,
  });

  return createHash("sha256").update(payload).digest("hex");
}

function isDuplicateKeyError(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: string }).code === "ER_DUP_ENTRY"
  );
}

async function fetchSnapshotById(
  db: KyselySchema,
  companyId: number,
  snapshotId: number
): Promise<APReconciliationSnapshotRecord> {
  const result = await sql<SnapshotRow>`
    SELECT
      id,
      company_id,
      as_of_date,
      timezone,
      snapshot_version,
      ap_subledger_balance,
      gl_control_balance,
      variance,
      configured_account_ids_json,
      account_source,
      inputs_hash,
      created_by,
      created_at,
      auto_generated,
      status,
      retention_policy_years,
      archived_at,
      archive_version
    FROM ap_reconciliation_snapshots
    WHERE company_id = ${companyId}
      AND id = ${snapshotId}
    LIMIT 1
  `.execute(db);

  if (result.rows.length === 0) {
    throw new APReconciliationSnapshotNotFoundError(snapshotId);
  }

  return mapSnapshotRow(result.rows[0]);
}

export async function createAPReconciliationSnapshot(input: {
  companyId: number;
  asOfDate: string;
  createdBy: number;
  autoGenerated?: boolean;
  reason?: string;
}): Promise<APReconciliationSnapshotRecord> {
  const db = getDb() as KyselySchema;

  const normalizedDate = normalizeDateOnly(input.asOfDate);
  const autoGenerated = input.autoGenerated === true;

  const summary = await getAPReconciliationSummary(input.companyId, normalizedDate);
  const timezone = await resolveCompanyTimezone(input.companyId);

  const configuredAccountIds = summary.configuredAccountIds;
  const configuredAccountIdsJson = JSON.stringify(configuredAccountIds);
  const inputsHash = computeInputsHash({
    companyId: input.companyId,
    asOfDate: normalizedDate,
    timezone,
    configuredAccountIds,
    accountSource: summary.accountSource,
    apSubledgerBalance: summary.apSubledgerBalance,
    glControlBalance: summary.glControlBalance,
    variance: summary.variance,
  });

  // Retry on unique-key contention (first snapshot race on empty chain).
  const MAX_RETRIES = 3;
  for (let attempt = 0; attempt < MAX_RETRIES; attempt += 1) {
    try {
      const createdSnapshot = await db.transaction().execute(async (trx) => {
        const previousSnapshotResult = await sql<SnapshotRow>`
      SELECT
        id,
        company_id,
        as_of_date,
        timezone,
        snapshot_version,
        ap_subledger_balance,
        gl_control_balance,
        variance,
        configured_account_ids_json,
        account_source,
        inputs_hash,
        created_by,
        created_at,
        auto_generated,
        status,
        retention_policy_years,
        archived_at,
        archive_version
      FROM ap_reconciliation_snapshots
      WHERE company_id = ${input.companyId}
        AND as_of_date = ${normalizedDate}
      ORDER BY snapshot_version DESC
      LIMIT 1
      FOR UPDATE
    `.execute(trx);

        const previous = previousSnapshotResult.rows.length > 0
          ? mapSnapshotRow(previousSnapshotResult.rows[0])
          : null;

        // Idempotent auto trigger: if same effective inputs already captured by latest
        // auto snapshot for the date, return existing snapshot instead of version bump.
        if (
          autoGenerated &&
          previous &&
          previous.autoGenerated &&
          previous.inputsHash === inputsHash
        ) {
          return previous;
        }

        const nextVersion = (previous?.snapshotVersion ?? 0) + 1;

        const insertResult = await sql`
      INSERT INTO ap_reconciliation_snapshots (
        company_id,
        as_of_date,
        timezone,
        snapshot_version,
        ap_subledger_balance,
        gl_control_balance,
        variance,
        configured_account_ids_json,
        account_source,
        inputs_hash,
        created_by,
        auto_generated,
        status,
        retention_policy_years
      ) VALUES (
        ${input.companyId},
        ${normalizedDate},
        ${timezone},
        ${nextVersion},
        ${summary.apSubledgerBalance},
        ${summary.glControlBalance},
        ${summary.variance},
        ${configuredAccountIdsJson},
        ${summary.accountSource},
        ${inputsHash},
        ${input.createdBy},
        ${autoGenerated ? 1 : 0},
        'ACTIVE',
        NULL
      )
    `.execute(trx);

        const insertedSnapshotId = Number((insertResult as { insertId?: number }).insertId ?? 0);

        if (previous) {
          await sql`
            UPDATE ap_reconciliation_snapshots
            SET superseded_by_snapshot_id = ${insertedSnapshotId}
            WHERE company_id = ${input.companyId}
              AND id = ${previous.id}
              AND superseded_by_snapshot_id IS NULL
          `.execute(trx);
        }

        await sql`
      INSERT INTO ap_reconciliation_audit_trail (
        company_id,
        snapshot_id,
        previous_snapshot_id,
        action_type,
        change_summary,
        change_reason,
        changed_by,
        metadata
      ) VALUES (
        ${input.companyId},
        ${insertedSnapshotId},
        ${previous?.id ?? null},
        ${previous ? "RECALCULATED" : "CREATED"},
        ${JSON.stringify({
          before: previous
            ? {
                ap_subledger_balance: previous.apSubledgerBalance,
                gl_control_balance: previous.glControlBalance,
                variance: previous.variance,
                inputs_hash: previous.inputsHash,
              }
            : null,
          after: {
            ap_subledger_balance: summary.apSubledgerBalance,
            gl_control_balance: summary.glControlBalance,
            variance: summary.variance,
            inputs_hash: inputsHash,
          },
          changed_fields: previous
            ? [
                previous.apSubledgerBalance !== summary.apSubledgerBalance ? "ap_subledger_balance" : null,
                previous.glControlBalance !== summary.glControlBalance ? "gl_control_balance" : null,
                previous.variance !== summary.variance ? "variance" : null,
                previous.inputsHash !== inputsHash ? "inputs_hash" : null,
              ].filter((field): field is string => field !== null)
            : ["initial_snapshot"],
        })},
        ${input.reason ?? (autoGenerated ? "period_close_auto_snapshot" : "manual_snapshot")},
        ${input.createdBy},
        ${JSON.stringify({
          as_of_date: normalizedDate,
          account_source: summary.accountSource,
          configured_account_ids: configuredAccountIds,
        })}
      )
    `.execute(trx);

        return fetchSnapshotById(trx as KyselySchema, input.companyId, insertedSnapshotId);
      });

      return createdSnapshot;
    } catch (error) {
      if (isDuplicateKeyError(error) && attempt < MAX_RETRIES - 1) {
        continue;
      }
      throw error;
    }
  }

  throw new Error("Failed to create AP reconciliation snapshot");
}

export async function listAPReconciliationSnapshots(
  companyId: number,
  filters: SnapshotListFilters
): Promise<{ items: APReconciliationSnapshotRecord[]; totalCount: number }> {
  const db = getDb() as KyselySchema;

  const asOfDateCondition = filters.asOfDate
    ? sql`AND as_of_date = ${normalizeDateOnly(filters.asOfDate)}`
    : sql``;
  const startDateCondition = filters.startDate
    ? sql`AND as_of_date >= ${normalizeDateOnly(filters.startDate)}`
    : sql``;
  const endDateCondition = filters.endDate
    ? sql`AND as_of_date <= ${normalizeDateOnly(filters.endDate)}`
    : sql``;
  const autoGeneratedCondition = filters.autoGenerated !== undefined
    ? sql`AND auto_generated = ${filters.autoGenerated ? 1 : 0}`
    : sql``;

  const rowsResult = await sql<SnapshotRow>`
    SELECT
      id,
      company_id,
      as_of_date,
      timezone,
      snapshot_version,
      ap_subledger_balance,
      gl_control_balance,
      variance,
      configured_account_ids_json,
      account_source,
      inputs_hash,
      created_by,
      created_at,
      auto_generated,
      status,
      retention_policy_years,
      archived_at,
      archive_version
    FROM ap_reconciliation_snapshots
    WHERE company_id = ${companyId}
    ${asOfDateCondition}
    ${startDateCondition}
    ${endDateCondition}
    ${autoGeneratedCondition}
    ORDER BY as_of_date DESC, snapshot_version DESC
    LIMIT ${filters.limit}
    OFFSET ${filters.offset}
  `.execute(db);

  const countResult = await sql<{ total_count: number }>`
    SELECT COUNT(*) AS total_count
    FROM ap_reconciliation_snapshots
    WHERE company_id = ${companyId}
    ${asOfDateCondition}
    ${startDateCondition}
    ${endDateCondition}
    ${autoGeneratedCondition}
  `.execute(db);

  const items = rowsResult.rows.map((row) => mapSnapshotRow(row));
  const totalCount = Number(countResult.rows[0]?.total_count ?? 0);

  return { items, totalCount };
}

export async function getAPReconciliationSnapshotById(
  companyId: number,
  snapshotId: number
): Promise<APReconciliationSnapshotRecord> {
  const db = getDb() as KyselySchema;
  return fetchSnapshotById(db, companyId, snapshotId);
}

export async function compareAPReconciliationSnapshots(input: {
  companyId: number;
  snapshotId: number;
  withSnapshotId: number;
}): Promise<SnapshotCompareResult> {
  const db = getDb() as KyselySchema;

  const baseSnapshot = await fetchSnapshotById(db, input.companyId, input.snapshotId);
  const otherSnapshot = await fetchSnapshotById(db, input.companyId, input.withSnapshotId);

  if (baseSnapshot.companyId !== otherSnapshot.companyId) {
    throw new APReconciliationSnapshotCompareCrossTenantError(input.snapshotId, input.withSnapshotId);
  }

  const changedFields: string[] = [];
  if (baseSnapshot.apSubledgerBalance !== otherSnapshot.apSubledgerBalance) {
    changedFields.push("ap_subledger_balance");
  }
  if (baseSnapshot.glControlBalance !== otherSnapshot.glControlBalance) {
    changedFields.push("gl_control_balance");
  }
  if (baseSnapshot.variance !== otherSnapshot.variance) {
    changedFields.push("variance");
  }
  if (baseSnapshot.inputsHash !== otherSnapshot.inputsHash) {
    changedFields.push("inputs_hash");
  }
  if (baseSnapshot.snapshotVersion !== otherSnapshot.snapshotVersion) {
    changedFields.push("snapshot_version");
  }

  return {
    baseSnapshot,
    otherSnapshot,
    delta: {
      apSubledgerBalance: computeDelta(baseSnapshot.apSubledgerBalance, otherSnapshot.apSubledgerBalance),
      glControlBalance: computeDelta(baseSnapshot.glControlBalance, otherSnapshot.glControlBalance),
      variance: computeDelta(baseSnapshot.variance, otherSnapshot.variance),
    },
    changedFields,
  };
}

function escapeCsv(value: string): string {
  if (value.includes(",") || value.includes("\"") || value.includes("\n")) {
    return `"${value.replaceAll("\"", "\"\"")}"`;
  }
  return value;
}

export function generateSnapshotCSV(snapshot: APReconciliationSnapshotRecord): string {
  const header = [
    "snapshot_id",
    "company_id",
    "as_of_date",
    "snapshot_version",
    "auto_generated",
    "account_source",
    "configured_account_ids",
    "ap_subledger_balance",
    "gl_control_balance",
    "variance",
    "timezone",
    "inputs_hash",
    "created_by",
    "created_at",
    "status",
  ];

  const row = [
    String(snapshot.id),
    String(snapshot.companyId),
    snapshot.asOfDate,
    String(snapshot.snapshotVersion),
    snapshot.autoGenerated ? "true" : "false",
    snapshot.accountSource,
    JSON.stringify(snapshot.configuredAccountIds),
    snapshot.apSubledgerBalance,
    snapshot.glControlBalance,
    snapshot.variance,
    snapshot.timezone,
    snapshot.inputsHash,
    String(snapshot.createdBy),
    snapshot.createdAt,
    snapshot.status,
  ];

  return `${header.join(",")}\n${row.map(escapeCsv).join(",")}\n`;
}
