// Copyright (c) 2026 Ahmad Faruk (Signal18 ID). All rights reserved.
// Ownership: Ahmad Faruk (Signal18 ID)

/**
 * AP Reconciliation Snapshot types for purchasing module.
 */

export type SnapshotStatus = "ACTIVE" | "ARCHIVED";

export interface APReconciliationSnapshotRecord {
  id: number;
  companyId: number;
  asOfDate: string;
  timezone: string;
  snapshotVersion: number;
  apSubledgerBalance: string;
  glControlBalance: string;
  variance: string;
  configuredAccountIds: number[];
  accountSource: "settings" | "fallback_company_default" | "none";
  inputsHash: string;
  createdBy: number;
  createdAt: string;
  autoGenerated: boolean;
  status: SnapshotStatus;
  retentionPolicyYears: number | null;
  archivedAt: string | null;
  archiveVersion: string | null;
}

export interface SnapshotListFilters {
  asOfDate?: string;
  startDate?: string;
  endDate?: string;
  autoGenerated?: boolean;
  limit: number;
  offset: number;
}

export interface SnapshotCompareResult {
  baseSnapshot: APReconciliationSnapshotRecord;
  otherSnapshot: APReconciliationSnapshotRecord;
  delta: {
    apSubledgerBalance: string;
    glControlBalance: string;
    variance: string;
  };
  changedFields: string[];
}

export class APReconciliationSnapshotNotFoundError extends Error {
  constructor(snapshotId: number) {
    super(`AP reconciliation snapshot ${snapshotId} not found`);
    this.name = "APReconciliationSnapshotNotFoundError";
  }
}

export class APReconciliationSnapshotCompareCrossTenantError extends Error {
  constructor(baseSnapshotId: number, otherSnapshotId: number) {
    super(
      `Cannot compare snapshots ${baseSnapshotId} and ${otherSnapshotId}: snapshots must belong to the same tenant`
    );
    this.name = "APReconciliationSnapshotCompareCrossTenantError";
  }
}

export interface CreateAPReconciliationSnapshotParams {
  companyId: number;
  asOfDate: string;
  createdBy: number;
  autoGenerated?: boolean;
  reason?: string;
}

export interface ListAPReconciliationSnapshotsParams {
  companyId: number;
  filters: SnapshotListFilters;
}

export interface GetAPReconciliationSnapshotByIdParams {
  companyId: number;
  snapshotId: number;
}

export interface CompareAPReconciliationSnapshotsParams {
  companyId: number;
  snapshotId: number;
  withSnapshotId: number;
}

export interface GenerateSnapshotCSVParams {
  snapshot: APReconciliationSnapshotRecord;
}
