CREATE TABLE IF NOT EXISTS sales_invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  outlet_id BIGINT UNSIGNED NOT NULL,
  invoice_no VARCHAR(64) NOT NULL,
  invoice_date DATE NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
  payment_status VARCHAR(16) NOT NULL DEFAULT 'UNPAID',
  subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  grand_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  paid_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  created_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  updated_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sales_invoices_company_invoice_no (company_id, invoice_no),
  KEY idx_sales_invoices_company_invoice_date (company_id, invoice_date),
  KEY idx_sales_invoices_outlet_invoice_date (outlet_id, invoice_date),
  KEY idx_sales_invoices_company_status (company_id, status),
  KEY idx_sales_invoices_company_payment_status (company_id, payment_status),
  KEY idx_sales_invoices_scope_id (company_id, outlet_id, id),
  CONSTRAINT chk_sales_invoices_status CHECK (status IN ('DRAFT', 'POSTED', 'VOID')),
  CONSTRAINT chk_sales_invoices_payment_status CHECK (payment_status IN ('UNPAID', 'PARTIAL', 'PAID')),
  CONSTRAINT chk_sales_invoices_subtotal_non_negative CHECK (subtotal >= 0),
  CONSTRAINT chk_sales_invoices_tax_amount_non_negative CHECK (tax_amount >= 0),
  CONSTRAINT chk_sales_invoices_grand_total_non_negative CHECK (grand_total >= 0),
  CONSTRAINT chk_sales_invoices_paid_total_non_negative CHECK (paid_total >= 0),
  CONSTRAINT chk_sales_invoices_paid_total_lte_grand_total CHECK (paid_total <= grand_total),
  CONSTRAINT chk_sales_invoices_grand_total_formula CHECK (grand_total = subtotal + tax_amount),
  CONSTRAINT fk_sales_invoices_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_sales_invoices_outlet_scoped FOREIGN KEY (company_id, outlet_id) REFERENCES outlets(company_id, id),
  CONSTRAINT fk_sales_invoices_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_sales_invoices_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sales_invoice_lines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_id BIGINT UNSIGNED NOT NULL,
  company_id BIGINT UNSIGNED NOT NULL,
  outlet_id BIGINT UNSIGNED NOT NULL,
  line_no INT UNSIGNED NOT NULL,
  description VARCHAR(255) NOT NULL,
  qty DECIMAL(18,4) NOT NULL,
  unit_price DECIMAL(18,2) NOT NULL,
  line_total DECIMAL(18,2) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sales_invoice_lines_invoice_line_no (invoice_id, line_no),
  KEY idx_sales_invoice_lines_company_created_at (company_id, created_at),
  KEY idx_sales_invoice_lines_outlet_created_at (outlet_id, created_at),
  KEY idx_sales_invoice_lines_scope_invoice (company_id, outlet_id, invoice_id),
  CONSTRAINT chk_sales_invoice_lines_qty_positive CHECK (qty > 0),
  CONSTRAINT chk_sales_invoice_lines_unit_price_non_negative CHECK (unit_price >= 0),
  CONSTRAINT chk_sales_invoice_lines_line_total_non_negative CHECK (line_total >= 0),
  CONSTRAINT fk_sales_invoice_lines_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_sales_invoice_lines_outlet_scoped FOREIGN KEY (company_id, outlet_id) REFERENCES outlets(company_id, id),
  CONSTRAINT fk_sales_invoice_lines_invoice_scoped FOREIGN KEY (company_id, outlet_id, invoice_id) REFERENCES sales_invoices(company_id, outlet_id, id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sales_payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  outlet_id BIGINT UNSIGNED NOT NULL,
  invoice_id BIGINT UNSIGNED NOT NULL,
  payment_no VARCHAR(64) NOT NULL,
  payment_at DATETIME NOT NULL,
  method VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
  amount DECIMAL(18,2) NOT NULL,
  created_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  updated_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sales_payments_company_payment_no (company_id, payment_no),
  KEY idx_sales_payments_company_payment_at (company_id, payment_at),
  KEY idx_sales_payments_outlet_payment_at (outlet_id, payment_at),
  KEY idx_sales_payments_company_status (company_id, status),
  KEY idx_sales_payments_company_invoice_status (company_id, invoice_id, status),
  KEY idx_sales_payments_scope_id (company_id, outlet_id, id),
  KEY idx_sales_payments_scope_invoice (company_id, outlet_id, invoice_id),
  CONSTRAINT chk_sales_payments_status CHECK (status IN ('DRAFT', 'POSTED', 'VOID')),
  CONSTRAINT chk_sales_payments_method CHECK (method IN ('CASH', 'QRIS', 'CARD')),
  CONSTRAINT chk_sales_payments_amount_positive CHECK (amount > 0),
  CONSTRAINT fk_sales_payments_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_sales_payments_outlet_scoped FOREIGN KEY (company_id, outlet_id) REFERENCES outlets(company_id, id),
  CONSTRAINT fk_sales_payments_invoice_scoped FOREIGN KEY (company_id, outlet_id, invoice_id) REFERENCES sales_invoices(company_id, outlet_id, id),
  CONSTRAINT fk_sales_payments_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_sales_payments_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
