-- Copyright (c) 2026 Ahmad Faruk (Signal18 ID). All rights reserved.
-- Ownership: Ahmad Faruk (Signal18 ID)

CREATE TABLE IF NOT EXISTS asset_depreciation_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  asset_id BIGINT UNSIGNED NOT NULL,
  outlet_id BIGINT UNSIGNED DEFAULT NULL,
  method VARCHAR(32) NOT NULL DEFAULT 'STRAIGHT_LINE',
  start_date DATE NOT NULL,
  useful_life_months INT UNSIGNED NOT NULL,
  salvage_value DECIMAL(18,2) NOT NULL DEFAULT 0,
  purchase_cost_snapshot DECIMAL(18,2) NOT NULL,
  expense_account_id BIGINT UNSIGNED NOT NULL,
  accum_depr_account_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_depr_plans_company_asset (company_id, asset_id),
  KEY idx_depr_plans_company_status (company_id, status),
  CONSTRAINT chk_depr_plans_method CHECK (method IN ('STRAIGHT_LINE')),
  CONSTRAINT chk_depr_plans_status CHECK (status IN ('DRAFT', 'ACTIVE', 'VOID')),
  CONSTRAINT chk_depr_plans_useful_life_positive CHECK (useful_life_months > 0),
  CONSTRAINT chk_depr_plans_salvage_non_negative CHECK (salvage_value >= 0),
  CONSTRAINT chk_depr_plans_purchase_cost_non_negative CHECK (purchase_cost_snapshot >= 0),
  CONSTRAINT fk_depr_plans_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_depr_plans_asset FOREIGN KEY (asset_id) REFERENCES fixed_assets(id),
  CONSTRAINT fk_depr_plans_outlet FOREIGN KEY (outlet_id) REFERENCES outlets(id),
  CONSTRAINT fk_depr_plans_expense_account FOREIGN KEY (expense_account_id) REFERENCES accounts(id),
  CONSTRAINT fk_depr_plans_accum_account FOREIGN KEY (accum_depr_account_id) REFERENCES accounts(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS asset_depreciation_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  plan_id BIGINT UNSIGNED NOT NULL,
  period_year INT UNSIGNED NOT NULL,
  period_month TINYINT UNSIGNED NOT NULL,
  run_date DATE NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  journal_batch_id BIGINT UNSIGNED DEFAULT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'POSTED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_depr_runs_plan_period (plan_id, period_year, period_month),
  KEY idx_depr_runs_company_period (company_id, period_year, period_month),
  KEY idx_depr_runs_company_status (company_id, status),
  CONSTRAINT chk_depr_runs_period_month CHECK (period_month BETWEEN 1 AND 12),
  CONSTRAINT chk_depr_runs_amount_non_negative CHECK (amount >= 0),
  CONSTRAINT chk_depr_runs_status CHECK (status IN ('POSTED', 'VOID')),
  CONSTRAINT fk_depr_runs_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_depr_runs_plan FOREIGN KEY (plan_id) REFERENCES asset_depreciation_plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_depr_runs_journal_batch FOREIGN KEY (journal_batch_id) REFERENCES journal_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB;
