-- Copyright (c) 2026 Ahmad Faruk (Signal18 ID). All rights reserved.
-- Ownership: Ahmad Faruk (Signal18 ID)

-- Migration: 0207_seed_canonical_acl_all_companies
-- Description: Seed canonical module_roles (company-level) for ALL existing companies
-- Source of truth: @jurnapod/shared/src/constants/roles.defaults.json (179 entries, 95 groups)
-- Generated by: packages/db/scripts/generate-acl-migration.mjs
-- Strategy: INSERT IGNORE ... CROSS JOIN companies × roles — safe to re-run
-- Compatible with: MySQL 8.0+, MariaDB 10.2+

-- ============================================================================
-- Part 1: Upsert module entries
-- ============================================================================

INSERT INTO modules (code, name) VALUES ('accounting', 'Accounting')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = CURRENT_TIMESTAMP;

INSERT INTO modules (code, name) VALUES ('inventory', 'Inventory')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = CURRENT_TIMESTAMP;

INSERT INTO modules (code, name) VALUES ('platform', 'Platform')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = CURRENT_TIMESTAMP;

INSERT INTO modules (code, name) VALUES ('pos', 'Pos')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = CURRENT_TIMESTAMP;

INSERT INTO modules (code, name) VALUES ('purchasing', 'Purchasing')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = CURRENT_TIMESTAMP;

INSERT INTO modules (code, name) VALUES ('reservations', 'Reservations')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = CURRENT_TIMESTAMP;

INSERT INTO modules (code, name) VALUES ('sales', 'Sales')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = CURRENT_TIMESTAMP;

INSERT INTO modules (code, name) VALUES ('treasury', 'Treasury')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = CURRENT_TIMESTAMP;

-- ============================================================================
-- Part 2: Seed company-level module_roles for ALL roles × modules × resources
-- ============================================================================

SET FOREIGN_KEY_CHECKS=0;
SET UNIQUE_CHECKS=0;

-- accounting.accounts = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'accounts', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- accounting.accounts = 1 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'accounts', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- accounting.accounts = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'accounts', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- accounting.fiscal_years = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'fiscal_years', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- accounting.fiscal_years = 1 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'fiscal_years', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- accounting.fiscal_years = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'fiscal_years', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- accounting.journals = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'journals', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- accounting.journals = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'journals', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- accounting.journals = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'journals', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- accounting.reports = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'reports', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- accounting.reports = 1 → ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'reports', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN');

-- accounting.reports = 31 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'reports', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- accounting.reports = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'accounting', 'reports', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- inventory.costing = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'costing', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- inventory.costing = 1 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'costing', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- inventory.costing = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'costing', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- inventory.items = 1 → ACCOUNTANT, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'items', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'CASHIER');

-- inventory.items = 31 → ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'items', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN');

-- inventory.items = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'items', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- inventory.stock = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'stock', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- inventory.stock = 1 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'stock', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- inventory.stock = 31 → ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'stock', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN');

-- inventory.stock = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'inventory', 'stock', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- platform.companies = 0 → ACCOUNTANT, ADMIN, CASHIER, COMPANY_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'companies', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN', 'CASHIER', 'COMPANY_ADMIN');

-- platform.companies = 5 → OWNER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'companies', 5
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('OWNER');

-- platform.companies = 63 → SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'companies', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('SUPER_ADMIN');

-- platform.customers = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'customers', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- platform.customers = 1 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'customers', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- platform.customers = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'customers', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- platform.outlets = 1 → ACCOUNTANT, ADMIN, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'outlets', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN', 'CASHIER');

-- platform.outlets = 31 → COMPANY_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'outlets', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN');

-- platform.outlets = 63 → OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'outlets', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('OWNER', 'SUPER_ADMIN');

-- platform.roles = 0 → ACCOUNTANT, CASHIER, COMPANY_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'roles', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'CASHIER', 'COMPANY_ADMIN');

-- platform.roles = 1 → ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'roles', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN');

-- platform.roles = 63 → OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'roles', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('OWNER', 'SUPER_ADMIN');

-- platform.settings = 0 → ACCOUNTANT, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'settings', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'CASHIER');

-- platform.settings = 1 → ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'settings', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN');

-- platform.settings = 31 → COMPANY_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'settings', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN');

-- platform.settings = 63 → OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'settings', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('OWNER', 'SUPER_ADMIN');

-- platform.users = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'users', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- platform.users = 1 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'users', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- platform.users = 31 → COMPANY_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'users', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN');

-- platform.users = 63 → OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'platform', 'users', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('OWNER', 'SUPER_ADMIN');

-- pos.config = 0 → ACCOUNTANT, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'pos', 'config', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'CASHIER');

-- pos.config = 31 → ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'pos', 'config', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN');

-- pos.config = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'pos', 'config', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- pos.transactions = 0 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'pos', 'transactions', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- pos.transactions = 31 → ADMIN, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'pos', 'transactions', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN', 'CASHIER');

-- pos.transactions = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'pos', 'transactions', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- purchasing.credits = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'credits', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- purchasing.credits = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'credits', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- purchasing.credits = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'credits', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- purchasing.exchange_rates = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'exchange_rates', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- purchasing.exchange_rates = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'exchange_rates', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- purchasing.exchange_rates = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'exchange_rates', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- purchasing.invoices = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'invoices', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- purchasing.invoices = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'invoices', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- purchasing.invoices = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'invoices', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- purchasing.orders = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'orders', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- purchasing.orders = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'orders', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- purchasing.orders = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'orders', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- purchasing.payments = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'payments', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- purchasing.payments = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'payments', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- purchasing.payments = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'payments', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- purchasing.receipts = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'receipts', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- purchasing.receipts = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'receipts', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- purchasing.receipts = 63 → OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'receipts', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('OWNER', 'SUPER_ADMIN');

-- purchasing.reports = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'reports', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- purchasing.reports = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'reports', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- purchasing.reports = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'reports', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- purchasing.suppliers = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'suppliers', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- purchasing.suppliers = 31 → ACCOUNTANT, ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'suppliers', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN');

-- purchasing.suppliers = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'purchasing', 'suppliers', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- reservations.bookings = 0 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'reservations', 'bookings', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- reservations.bookings = 31 → ADMIN, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'reservations', 'bookings', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN', 'CASHIER');

-- reservations.bookings = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'reservations', 'bookings', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- reservations.tables = 0 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'reservations', 'tables', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- reservations.tables = 1 → ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'reservations', 'tables', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN');

-- reservations.tables = 31 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'reservations', 'tables', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- reservations.tables = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'reservations', 'tables', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- sales.invoices = 1 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'invoices', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- sales.invoices = 31 → ADMIN, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'invoices', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN', 'CASHIER');

-- sales.invoices = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'invoices', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- sales.orders = 1 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'orders', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- sales.orders = 31 → ADMIN, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'orders', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN', 'CASHIER');

-- sales.orders = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'orders', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- sales.payments = 1 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'payments', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- sales.payments = 31 → ADMIN, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'payments', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN', 'CASHIER');

-- sales.payments = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'sales', 'payments', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- treasury.accounts = 1 → ACCOUNTANT, ADMIN, CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'treasury', 'accounts', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT', 'ADMIN', 'CASHIER');

-- treasury.accounts = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'treasury', 'accounts', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

-- treasury.transactions = 0 → CASHIER
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'treasury', 'transactions', 0
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('CASHIER');

-- treasury.transactions = 1 → ACCOUNTANT
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'treasury', 'transactions', 1
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ACCOUNTANT');

-- treasury.transactions = 31 → ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'treasury', 'transactions', 31
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('ADMIN');

-- treasury.transactions = 63 → COMPANY_ADMIN, OWNER, SUPER_ADMIN
INSERT IGNORE INTO module_roles (company_id, role_id, module, resource, permission_mask)
SELECT c.id AS company_id, r.id AS role_id, 'treasury', 'transactions', 63
FROM companies c
CROSS JOIN roles r
WHERE r.code IN ('COMPANY_ADMIN', 'OWNER', 'SUPER_ADMIN');

SET FOREIGN_KEY_CHECKS=1;
SET UNIQUE_CHECKS=1;
