// Copyright (c) 2026 Ahmad Faruk (Signal18 ID). All rights reserved.
// Ownership: Ahmad Faruk (Signal18 ID)

/**
 * Fiscal Year API Adapter
 * 
 * Thin adapter layer that bridges the API to the fiscal-year domain service
 * in @jurnapod/modules-accounting.
 * 
 * This file re-exports domain types/errors from the package and provides
 * backward-compatible wrapper functions that use getDb() internally.
 */

import type { KyselySchema } from "@jurnapod/db";
import type {
  FiscalYear,
  FiscalYearCreateRequest,
  FiscalYearListQuery,
  FiscalYearUpdateRequest
} from "@jurnapod/shared";
import { getDb } from "./db.js";
import { KyselySettingsAdapter } from "@jurnapod/modules-platform/settings";


import {
  FiscalYearService,
  type FiscalYearSettingsPort,
  type FiscalYearDbClient,
  type CloseFiscalYearContext,
  type CloseFiscalYearResult,
  type ClosePreviewResult,
  type FiscalYearStatusResult,
} from "@jurnapod/modules-accounting/fiscal-year";
import {
  JournalsService,
  checkGlImbalanceByBatchId,
  type JournalsDbClient,
} from "@jurnapod/modules-accounting";
import { createAPReconciliationSnapshot } from "./purchasing/ap-reconciliation-snapshots.js";

// Re-export types from package
export {
  type CloseFiscalYearContext,
  type CloseFiscalYearResult,
  type ClosePreviewResult,
  type FiscalYearStatusResult,
  FISCAL_YEAR_CLOSE_STATUS,
  type FiscalYearCloseStatus,
  type ClosingEntryLine,
  type PeriodStatus
} from "@jurnapod/modules-accounting/fiscal-year";

// Re-export errors from package
export {
  FiscalYearNotFoundError,
  FiscalYearCodeExistsError,
  FiscalYearDateRangeError,
  FiscalYearOverlapError,
  FiscalYearOpenConflictError,
  FiscalYearNotOpenError,
  FiscalYearSelectionError,
  FiscalYearAlreadyClosedError,
  FiscalYearCloseConflictError,
  FiscalYearClosePreconditionError,
  FiscalYearClosePreviewError,
  RetainedEarningsAccountNotFoundError
} from "@jurnapod/modules-accounting/fiscal-year";

// Create a settings port implementation using KyselySettingsAdapter
function createSettingsPort(db: KyselySchema): FiscalYearSettingsPort {
  const adapter = new KyselySettingsAdapter(db);
  return {
    async resolveBoolean(
      companyId: number,
      key: string,
      options?: { outletId?: number }
    ): Promise<boolean> {
      const value = await adapter.resolve<boolean>(companyId, key as any, {
        outletId: options?.outletId
      });
      return Boolean(value);
    }
  };
}

// Create a service instance getter (per-call factory)
function createFiscalYearService(): FiscalYearService {
  const db = getDb();
  const settings = createSettingsPort(db);
  return new FiscalYearService(db as FiscalYearDbClient, settings);
}

async function triggerAutoSnapshotForFiscalYearClose(input: {
  db: KyselySchema;
  companyId: number;
  fiscalYearId: number;
  requestedByUserId: number;
  closeRequestId: string;
  reasonPrefix: string;
}): Promise<void> {
  try {
    let snapshotActorUserId = input.requestedByUserId;
    if (!Number.isSafeInteger(snapshotActorUserId) || snapshotActorUserId <= 0) {
      const fallbackActor = await input.db
        .selectFrom("users")
        .where("company_id", "=", input.companyId)
        .select(["id"])
        .orderBy("id", "asc")
        .limit(1)
        .executeTakeFirst();

      if (!fallbackActor) {
        return;
      }

      snapshotActorUserId = Number(fallbackActor.id);
    }

    const fiscalYear = await input.db
      .selectFrom("fiscal_years")
      .where("company_id", "=", input.companyId)
      .where("id", "=", input.fiscalYearId)
      .select(["end_date"])
      .executeTakeFirst();

    if (fiscalYear?.end_date) {
      const asOfDate = fiscalYear.end_date instanceof Date
        ? fiscalYear.end_date.toISOString().slice(0, 10)
        : String(fiscalYear.end_date).slice(0, 10);

      await createAPReconciliationSnapshot({
        companyId: input.companyId,
        asOfDate,
        createdBy: snapshotActorUserId,
        autoGenerated: true,
        reason: `${input.reasonPrefix}:${input.closeRequestId}`,
      });
    }
  } catch (autoSnapshotError) {
    console.error("Auto AP reconciliation snapshot after fiscal year close failed", {
      companyId: input.companyId,
      fiscalYearId: input.fiscalYearId,
      closeRequestId: input.closeRequestId,
      autoSnapshotError,
    });
  }
}

// Wrapper functions that provide backward-compatible API

export async function listFiscalYears(query: FiscalYearListQuery): Promise<FiscalYear[]> {
  return createFiscalYearService().listFiscalYears(query);
}

export async function getFiscalYearById(
  companyId: number,
  fiscalYearId: number
): Promise<FiscalYear | null> {
  return createFiscalYearService().getFiscalYearById(companyId, fiscalYearId);
}

export async function createFiscalYear(
  input: FiscalYearCreateRequest,
  actorUserId?: number
): Promise<FiscalYear> {
  return createFiscalYearService().createFiscalYear(input, actorUserId);
}

export async function updateFiscalYear(
  companyId: number,
  fiscalYearId: number,
  input: FiscalYearUpdateRequest,
  actorUserId?: number
): Promise<FiscalYear | null> {
  return createFiscalYearService().updateFiscalYear(companyId, fiscalYearId, input, actorUserId);
}

export async function listOpenFiscalYearsForDate(
  companyId: number,
  date: string
): Promise<FiscalYear[]> {
  return createFiscalYearService().listOpenFiscalYearsForDate(companyId, date);
}

export async function ensureDateWithinOpenFiscalYear(
  companyId: number,
  date: string
): Promise<void> {
  return createFiscalYearService().ensureDateWithinOpenFiscalYear(companyId, date);
}

export async function ensureDateWithinOpenFiscalYearWithExecutor(
  db: KyselySchema,
  companyId: number,
  date: string
): Promise<void> {
  const service = new FiscalYearService(db as FiscalYearDbClient, createSettingsPort(db));
  return service.ensureDateWithinOpenFiscalYearWithExecutor(db as FiscalYearDbClient, companyId, date);
}

export async function resolveDefaultFiscalYearDateRange(
  companyId: number,
  referenceDate?: string
): Promise<{ dateFrom: string; dateTo: string }> {
  return createFiscalYearService().resolveDefaultFiscalYearDateRange(companyId, referenceDate);
}

export async function isFiscalYearClosed(
  db: KyselySchema,
  companyId: number,
  fiscalYearId: number
): Promise<boolean> {
  const service = new FiscalYearService(db as FiscalYearDbClient, createSettingsPort(db));
  return service.isFiscalYearClosed(companyId, fiscalYearId);
}

export async function closeFiscalYear(
  db: KyselySchema,
  fiscalYearId: number,
  closeRequestId: string,
  context: CloseFiscalYearContext,
  trx?: KyselySchema
): Promise<CloseFiscalYearResult> {
  const service = new FiscalYearService(db as FiscalYearDbClient, createSettingsPort(db));
  return service.closeFiscalYear(fiscalYearId, closeRequestId, context, trx as FiscalYearDbClient);
}

/**
 * Initiate fiscal year close (first step before approve).
 * 
 * This creates the idempotency record for the close request.
 * The actual close (status update to CLOSED) happens in approveFiscalYearClose.
 */
export async function initiateFiscalYearClose(
  fiscalYearId: number,
  closeRequestId: string,
  context: CloseFiscalYearContext
): Promise<CloseFiscalYearResult> {
  const db = getDb();
  const service = new FiscalYearService(db as FiscalYearDbClient, createSettingsPort(db));
  const closeResult = await service.closeFiscalYear(fiscalYearId, closeRequestId, context);

  if (closeResult.success && closeResult.newStatus === "CLOSED") {
    await triggerAutoSnapshotForFiscalYearClose({
      db: db as KyselySchema,
      companyId: context.companyId,
      fiscalYearId,
      requestedByUserId: context.requestedByUserId,
      closeRequestId,
      reasonPrefix: "fiscal_year_close_initiated",
    });
  }

  return closeResult;
}

export async function getFiscalYearClosePreview(
  companyId: number,
  fiscalYearId: number,
  dbOrTrx?: KyselySchema
): Promise<ClosePreviewResult> {
  const db = dbOrTrx ?? getDb();
  const service = new FiscalYearService(db as FiscalYearDbClient, createSettingsPort(db));
  return service.getFiscalYearClosePreview(companyId, fiscalYearId);
}

export async function getFiscalYearStatus(
  companyId: number,
  fiscalYearId: number
): Promise<FiscalYearStatusResult> {
  return createFiscalYearService().getFiscalYearStatus(companyId, fiscalYearId);
}

// =============================================================================
// Fiscal Year Close Approve Flow
// =============================================================================

/**
 * Result of the fiscal year close approve operation.
 */
export interface ApproveFiscalYearCloseResult {
  success: boolean;
  fiscalYearId: number;
  closeRequestId: string;
  status: string;
  previousStatus: string;
  newStatus: string;
  postedBatchIds: number[];
  netIncome: number;
  totalIncome: number;
  totalExpenses: number;
  hasImbalance: boolean;
  imbalanceDetails?: {
    batchId: number;
    imbalance: number;
  };
}

/**
 * Approve and execute fiscal year close with journal posting.
 * 
 * This function encapsulates the full close/approve flow:
 * 1. Get close preview (P&L balances, retained earnings account)
 * 2. Post closing journal entries within a transaction
 * 3. Check for GL imbalance
 * 4. Update fiscal year status to CLOSED
 * 
 * All operations are atomic - either all succeed or all rollback.
 */
export async function approveFiscalYearClose(
  companyId: number,
  fiscalYearId: number,
  closeRequestId: string,
  context: CloseFiscalYearContext
): Promise<ApproveFiscalYearCloseResult> {
  const db = getDb();

  const closeResult = await db.transaction().execute(async (tx) => {
    const journalsService = new JournalsService(tx as JournalsDbClient);

    // 1. Get preview within transaction for consistent reads
    const preview = await getFiscalYearClosePreview(companyId, fiscalYearId, tx as KyselySchema);

    const postedBatchIds: number[] = [];
    let hasImbalance = false;
    let imbalanceDetails: { batchId: number; imbalance: number } | null = null;

    if (preview.closingEntries.length > 0) {
      // Create a single balanced journal entry for all closing entries
      const lines = preview.closingEntries.map(entry => ({
        account_id: entry.accountId,
        debit: entry.debit,
        credit: entry.credit,
        description: entry.description
      }));

      // Verify the entries balance using fixed-point precision (DECIMAL(19,4)).
      // Avoid floating-point drift for monetary totals.
      const MONEY_SCALE = 10_000;
      const toScaled = (value: number): number => Math.round(value * MONEY_SCALE);
      const totalDebitScaled = lines.reduce((sum, l) => sum + toScaled(l.debit), 0);
      const totalCreditScaled = lines.reduce((sum, l) => sum + toScaled(l.credit), 0);

      if (totalDebitScaled !== totalCreditScaled) {
        const totalDebit = totalDebitScaled / MONEY_SCALE;
        const totalCredit = totalCreditScaled / MONEY_SCALE;
        throw new Error(
          `ENTRIES_NOT_BALANCED:Closing entries are not balanced: debit=${totalDebit}, credit=${totalCredit}`
        );
      }

      // 2. Post journal entries within transaction
      const journalResult = await journalsService.createManualEntry(
        {
          company_id: companyId,
          entry_date: preview.entryDate,
          description: preview.description,
          lines
        },
        context.requestedByUserId,
        tx as KyselySchema
      );
      postedBatchIds.push(journalResult.id);

      // Check for GL imbalance within transaction - happens AFTER posting but BEFORE commit.
      const imbalanceResult = await checkGlImbalanceByBatchId(tx as KyselySchema, journalResult.id, companyId);
      if (imbalanceResult) {
        hasImbalance = true;
        imbalanceDetails = {
          batchId: imbalanceResult.journalBatchId,
          imbalance: imbalanceResult.imbalance
        };
        throw new Error(
          `ENTRIES_NOT_BALANCED:GL imbalance detected after posting (batch=${imbalanceResult.journalBatchId}, imbalance=${imbalanceResult.imbalance})`
        );
      }
    }

    // 3. Update fiscal year status within same transaction
    const closeResult = await closeFiscalYear(
      tx as KyselySchema,
      fiscalYearId,
      closeRequestId,
      {
        companyId: context.companyId,
        requestedByUserId: context.requestedByUserId,
        requestedAtEpochMs: context.requestedAtEpochMs,
        reason: `Fiscal year close approved. Posted ${postedBatchIds.length} closing entry batch(es).`
      },
      tx as KyselySchema
    );

    return {
      success: closeResult.success,
      fiscalYearId: closeResult.fiscalYearId,
      closeRequestId: closeResult.closeRequestId,
      status: closeResult.status,
      previousStatus: closeResult.previousStatus,
      newStatus: closeResult.newStatus,
      postedBatchIds,
      netIncome: preview.netIncome,
      totalIncome: preview.totalIncome,
      totalExpenses: preview.totalExpenses,
      hasImbalance,
      imbalanceDetails: imbalanceDetails ?? undefined
    };
  });

  if (closeResult.success && closeResult.newStatus === "CLOSED") {
    await triggerAutoSnapshotForFiscalYearClose({
      db: db as KyselySchema,
      companyId,
      fiscalYearId,
      requestedByUserId: context.requestedByUserId,
      closeRequestId,
      reasonPrefix: "fiscal_year_close_approved",
    });
  }

  return closeResult;
}
