#!/usr/bin/env npx tsx
/**
 * validate-maketag-policy.ts
 *
 * Lightweight enforcement script for makeTag policy (F-determinism):
 * Detects obvious `.slice()` / `.substring()` anti-patterns on makeTag() output
 * in API integration test files.
 *
 * Usage:
 *   npx tsx scripts/validate-maketag-policy.ts
 *   npx tsx scripts/validate-maketag-policy.ts --fix   # list files only (no fix)
 *
 * Exits 0 if no violations found. Exits 1 with file:line:col report if violations exist.
 *
 * Policy (AGENTS.md F):
 *   Test/data tags generated by makeTag(...) MUST be treated as complete outputs.
 *   Contributors and agents MUST NOT apply post-generation slicing/truncation.
 *   Length constraints MUST be enforced inside the generator helper at creation time.
 */

import { readFileSync } from "fs";
import { join } from "path";

const API_TEST_PATH = join(process.cwd(), "apps/api/__test__/integration");

interface Violation {
  file: string;
  line: number;
  col: number;
  snippet: string;
}

// Pattern 1: makeTag(...).slice(...)
const PATTERN_1 = /makeTag\s*\([^)]*\)\s*\.(?:slice|substring|substr)\s*\(/g;
// Pattern 2: const t = makeTag(...); ... t.slice(...) or t.substring(...) or t.substr(...)
const PATTERN_2 = /\b(const|let|var)\s+\w+\s*=\s*makeTag\s*\([^)]*\)[^;]*;[^}]*?\.\s*(?:slice|substring|substr)\s*\(/gs;

function scanFile(filePath: string): Violation[] {
  const violations: Violation[] = [];
  let content: string;

  try {
    content = readFileSync(filePath, "utf-8");
  } catch {
    return violations; // skip unreadable
  }

  const lines = content.split("\n");

  // Pattern 1: makeTag(...).slice(...)
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Only check .slice( and .substring( and .substr( that are on the same line as makeTag
    // Match makeTag(...).slice( or makeTag(...).substring(
    const inlineSlice = /makeTag\s*\([^)]*\)\s*\.(?:slice|substring|substr)\s*\(/;
    if (inlineSlice.test(line)) {
      violations.push({
        file: filePath,
        line: i + 1,
        col: line.search(/\.slice|\.substring|\.substr/),
        snippet: line.trim(),
      });
    }
  }

  // Pattern 2: const t = makeTag(...); ... t.slice(...)
  // Find all makeTag variable assignments, then scan for their .slice usage within ~5 lines
  const makeTagAssignments: { name: string; line: number }[] = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const match = line.match(/(?:const|let|var)\s+(\w+)\s*=\s*makeTag\s*\(/);
    if (match) {
      makeTagAssignments.push({ name: match[1], line: i + 1 });
    }
  }

  for (const { name, line: assignLine } of makeTagAssignments) {
    // Scan up to 5 lines after the assignment for .slice/.substring/.substr on that variable
    const searchStart = assignLine - 1;
    const searchEnd = Math.min(searchStart + 6, lines.length);
    for (let i = searchStart; i < searchEnd; i++) {
      if (i === searchStart) continue; // skip the assignment line itself
      const line = lines[i];
      // Only match if the variable name is used and followed by .slice/.substring/.substr
      const varSlicePattern = new RegExp(`\\b${name}\\s*\\.\\s*(?:slice|substring|substr)\\s*\\(`);
      if (varSlicePattern.test(line)) {
        violations.push({
          file: filePath,
          line: i + 1,
          col: line.search(/\.slice|\.substring|\.substr/),
          snippet: line.trim(),
        });
      }
    }
  }

  return violations;
}

function scanDirectory(dir: string): Violation[] {
  const violations: Violation[] = [];
  const { readdirSync, statSync } = require("fs") as {
    readdirSync: (p: string) => string[];
    statSync: (p: string) => { isDirectory: () => boolean };
  };

  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return violations;
  }

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    try {
      const stat = statSync(fullPath);
      if (stat.isDirectory()) {
        violations.push(...scanDirectory(fullPath));
      } else if (entry.endsWith(".ts") && !entry.endsWith(".test.ts")) {
        violations.push(...scanFile(fullPath));
      }
    } catch {
      // skip
    }
  }

  return violations;
}

const allViolations = scanDirectory(API_TEST_PATH);

if (allViolations.length === 0) {
  console.log("✅ makeTag policy validation: no violations found");
  process.exit(0);
}

console.error(`❌ makeTag policy violations detected: ${allViolations.length}`);
for (const v of allViolations) {
  console.error(`  ${v.file}:${v.line}:${v.col} — ${v.snippet}`);
}
process.exit(1);