// Copyright (c) 2026 Ahmad Faruk (Signal18 ID). All rights reserved.
// Ownership: Ahmad Faruk (Signal18 ID)

import type { KyselySchema } from "@jurnapod/db";
import { ApReconciliationSnapshotService } from "../services/ap-reconciliation-snapshot-service.js";

/**
 * Fixture for ap_reconciliation_snapshots table (purchasing domain).
 *
 * Delegates to the production ApReconciliationSnapshotService.createAPReconciliationSnapshot()
 * to ensure test invariants match production invariants.
 *
 * Prerequisites (caller MUST satisfy):
 * - Company exists with a valid timezone
 * - Purchasing accounts exist (AP control account via company_modules or settings_strings)
 *
 * Used by AR snapshot trigger compatibility tests (Story 57.1) and reconciliation tests.
 */
export interface ReconciliationSnapshotFixture {
  id: number;
  companyId: number;
}

export interface CreateTestReconciliationSnapshotOpts {
  companyId: number;
  /** User ID for the created_by FK */
  userId: number;
  asOfDate?: string;
  /** If true, marks the snapshot as auto-generated (default: false) */
  autoGenerated?: boolean;
  /** Optional reason for audit trail */
  reason?: string;
}

export async function createTestReconciliationSnapshot(
  db: KyselySchema,
  opts: CreateTestReconciliationSnapshotOpts,
): Promise<ReconciliationSnapshotFixture> {
  const {
    companyId,
    userId,
    asOfDate = "2026-03-31",
    autoGenerated = false,
    reason,
  } = opts;

  const service = new ApReconciliationSnapshotService(db);
  const record = await service.createAPReconciliationSnapshot({
    companyId,
    asOfDate,
    createdBy: userId,
    autoGenerated,
    reason,
  });

  return {
    id: record.id,
    companyId: record.companyId,
  };
}
